### ISSUE TITLE
Can we get an 0.2.1 release?

### ISSUE THREAD

**Issue by lamont-granquist** [sj26/rspec_junit_formatter#18]
We need 96f0115f7dabbea623f04b60dc23519683f39cfa to release ohai and pinning to a gitsha in a Gemfile lock is trolling us pretty hard with windows+jenkins+azure and maybe our particular versions of git+bundler+rubygems+ruby but we haven't been able to repro anywhere else other than our CI boxes right now.

A release of this gem that we could pull from rubygems would avoid having to debug whatever is trolling us with trying to use the unreleased git branch.

**Comment by kylev** [comment]
Yes please. Another released version to rubygems would be rad. :+1: 

(After you merge my pull request, of course.)

**Comment by booleanbetrayal** [comment]
:+1: 

Currently pinned to master due to the above issue and would make keeping up with releases for this gem much less of a headache!

**Comment by sj26** [comment]
What harm could it do. Released!

Please let me know if you find any problems introduced by the release. I don't have an active jenkins/etc environment to test against.

**Comment by kylev** [comment]
Yay!
