### ISSUE TITLE
Add top level <testsuites> tag.

### ISSUE THREAD

**Issue by cyberdisk** [sj26/rspec_junit_formatter#20]
To make xml output fully compatible with standard one it makes sense to introduce a <testsuites> tag as top level.
I got an issue trying to submit xml reports into reporting tool and got an error that 'testsuites' is missing.

**Comment by sj26** [comment]
It doesn't seem that the standard requires a testsuites element as the root, at least according to the schema:

https://svn.jenkins-ci.org/trunk/hudson/dtkit/dtkit-format/dtkit-junit-model/src/main/resources/com/thalesgroup/dtkit/junit/model/xsd/junit-4.xsd

I'm hesitant to change what we currently do given we know that the current output works with the majority of cases.
