### ISSUE TITLE
Won't work with rspec 3 - gem issue

### ISSUE THREAD

**Issue by jantman** [sj26/rspec_junit_formatter#23]
The current 0.2.0 gem won't install with rspec3 under bundler, as this project's Gemfile specifies
    gem "rspec", "~> 2.14", "< 2.99"

**Comment by sj26** [comment]
Sorry, I don't think that's correct. The current requirements can be seen on the rubygems page: http://rubygems.org/gems/rspec_junit_formatter or on the gemspec in this repo: https://github.com/sj26/rspec_junit_formatter/blob/master/rspec_junit_formatter.gemspec

The gem is also tested against rspec 3 by Travis using bundler.
