### ISSUE TITLE
Not compatible with rspec-rails 3.2.1

### ISSUE THREAD

**Issue by warmwaffles** [sj26/rspec_junit_formatter#27]
Can not upgrade to `rspec-rails` `3.2.1` because of conflicts

```
Bundler could not find compatible versions for gem "rspec-mocks":
  In Gemfile:
    rspec_junit_formatter (~> 0.2.0) ruby depends on
      rspec (< 4, >= 2) ruby depends on
        rspec-mocks (~> 2.14.0) ruby

    rspec-rails (~> 3.2.1) ruby depends on
      rspec-mocks (3.2.0)
```

**Comment by sj26** [comment]
Sorry, looks like you've got a deeper dependency issue. rspec-rails 3.2.1 and rspec_junit_formatter work fine together:

https://gist.github.com/anonymous/3516846516634267b5d5

Maybe you need to `bundle update` so it can bump related dependencies.

**Comment by warmwaffles** [comment]
@sj26 thanks for the gist! This will help me a lot.

**Comment by warmwaffles** [comment]
Just as an update for future reference, I fixed this by removing the gem entirely, then running `bundle update` once everything was good, I added it back in and `bundle install` then it works just fine.
