### ISSUE TITLE
Pending Tests

### ISSUE THREAD

**Issue by smythey21** [sj26/rspec_junit_formatter#41]
I noticed that the test count provided includes pending tests, but there's no way to know how many are pending and how many tests are actually real tests. Couple things I think could be useful:
1. Include the number of pending tests in the output
2. Exclude pending tests from the test count 

I've already forked and made [these changes in my own branch](https://github.com/smythey21/rspec_junit_formatter/pull/1), let me know if you're interested and I can submit a PR

**Comment by sj26** [comment]
Sorry but I don't want to introduce unknown attributes or elements outside the junit schema as this breaks some parsers. You can get a count of pending tests pretty easily with an xpath like `count(//testcase[skipped])`.
