### ISSUE TITLE
Non-escaped double quotes break xml formatting, difficult to parse all data

### ISSUE THREAD

**Issue by esterlinej** [sj26/rspec_junit_formatter#48]
When parsing Artifact XML, I found that some of my peers have been using quotations in their test names, and these should be escaped when outputting to XML. It occurred to me that this issue may have not been known or reported, and hopefully will be addressed.

Example:
<testcase classname="./spec/controller/awesome_controller_spec.rb" name="using "double quotes" in the test name that doesn't necessarily break the XML file itself, but creates difficulty parsing through the file after the break in formatting" time="1.2345">

**Comment by sj26** [comment]
Hi there :wave: Thanks for the report! I think this may be solved the same as #48. Please try the latest pre-release (`gem install --pre rspec_junit_formatter` or in your Gemfile `gem "rspec_junit_formatter", ">= 0.3.0.pre"`) and let me know if you're still having trouble. Thanks!

**Comment by esterlinej** [comment]
Appreciated, I will check into this
