### ISSUE TITLE
Diffs contain ANSI codes

### ISSUE THREAD

**Issue by sj26** [sj26/rspec_junit_formatter#50]
The rspec differ's color output is controlled by the global color configuration and doesn't respect the notification and example result colorizers, per https://github.com/sj26/rspec_junit_formatter/issues/49#issuecomment-308479831.

We might need to use a clumsy regexp to detect colorized diff output and strip the ANSI codes.

Also investigating a better fix upstream in https://github.com/rspec/rspec-core/issues/2435.

**Comment by chrishough** [comment]
Were you able to fix this? I am having the same issue. Happy to help.

**Comment by sj26** [comment]
@chrishough have you tried version 0.3.0.pre6?

```sh
gem install rspec_junit_formatter --pre
```

or 

```ruby
gem "rspec_junit_formatter", "~> 0.3.0.pre6"
```

**Comment by chrishough** [comment]
I have been running a few tests so far yesterday and with this today.. 

**TEST ONE**
<img width="2381" alt="screen shot 2017-07-04 at 10 23 12 am" src="https://user-images.githubusercontent.com/744056/27838972-d24f0e66-60a2-11e7-925e-80968a839aee.png">
I removed `--color` from my `.rspec` file and I used `- RAILS_ENV=continous_integration bundle exec rspec --no-color --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec.xml` to run tests in circle ci.

👎 This resulted in no ansi symbols, however, the formatting is borked. 

**TEST TWO**
<img width="2395" alt="screen shot 2017-07-04 at 10 25 20 am" src="https://user-images.githubusercontent.com/744056/27839045-5bf14dfa-60a3-11e7-8fcd-e0a92ea20662.png">
I removed `--color` from my `.rspec` file, used the updated gem, and I used `- RAILS_ENV=continous_integration bundle exec rspec --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec.xml` to run tests in circle ci.  

👍 This resulted in no ansi symbols, and the formatting looks great.

**TEST THREE**

I also tried test two a second time with the `--no-color` flag. 

👍 This resulted in no ansi symbols, and the formatting looks great.

**TEST FOUR**
<img width="1580" alt="screen shot 2017-07-04 at 10 39 01 am" src="https://user-images.githubusercontent.com/744056/27839301-1764665c-60a5-11e7-80a6-62452e8c1bf0.png">

I left `--color` in my `.rspec` file, used the updated gem, and I used `- RAILS_ENV=continous_integration bundle exec rspec --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec.xml` to run tests in circle ci.  

👍 This resulted in no ansi symbols, and the formatting looks great.

**Comment by sj26** [comment]
Nice. I think 0.3.0 is ready for release.

**Comment by sj26** [comment]
v0.3.0 is out! It should fix this for most folks.

I'm going to work on pushing non-colored diffs upstream at some point, but this works for now.

**Comment by chrishough** [comment]
I upgraded to the latest @sj26 and my test cycles are still passing.
