### ISSUE TITLE
rspec_junit_formatter.rb:150:in `encode': "\xE3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

### ISSUE THREAD

**Issue by konstantin-psu** [sj26/rspec_junit_formatter#57]
Formatter tries to convert binary ASCII-8BIT to UTF8 without knowledge of encoding and fails since there are multiple resolutions.

One solution is to explicitly be able to set the desired encoding or tell it to ignore undefined and invalid characters (assuming data loss is acceptable)

For example:
text.to_s.encode('UTF-8', invalid: :replace, undef: :replace, replace: '?')

**Comment by sj26** [comment]
Please try updating to the latest version — v0.3.0 should fix this by encoding where possible and replacing where not.

**Comment by Poohblah** [comment]
@sj26 I'm on 0.4.1 and I'm still seeing this issue:

```
/tmp/verifier/gems/gems/rspec_junit_formatter-0.4.1/lib/rspec_junit_formatter.rb:165:in `encode': "\x80" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```
