### ISSUE TITLE
Reported time does not match reported RSpec time

### ISSUE THREAD

**Issue by kevinburkeomg** [sj26/rspec_junit_formatter#61]
For a recent build, RSpec (console) reported:

    Finished in 13 minutes 28 seconds (files took 23.36 seconds to load)

However, the RSpec XML generated for the same test run returned a much smaller number for the time:

```xml
<testsuite name="rspec" tests="1865" skipped="4" failures="0" errors="0" time="546.806313" timestamp="2018-06-11T16:25:59-07:00" hostname="27eb0b572fba">
```

546 seconds is 9 minutes, 6 seconds, so there are 4 minutes of unexplained difference in the timings. What could explain the discrepancy? I'm using junit formatter 0.3.0, but I checked the changelog and didn't see anything between then & tip that could explain a difference.

**Comment by sj26** [comment]
I double checked, we're reporting the same value as rspec's default text formatter. Sorry, but I'm not sure what's happened in your case. I suspect they were output from different rspec runs.
