### ISSUE TITLE
Invalid XML generated

### ISSUE THREAD

**Issue by bjeanes** [sj26/rspec_junit_formatter#69]
I'm not sure if this is a different occurrence of #33, but I am getting multiple RSpec steps generating XML that looks like the same contents written to file multiple times.

Originally reported on https://github.com/bugcrowd/test-summary-buildkite-plugin/issues/42 as that's where the I noticed the issue first.

I'm not sure what information at this point to provide to help track it down, but feel free to have a look at the artefact on my build: https://buildkite.com/covidence/app/builds/2533#81677cf4-bff2-4353-97e6-e40310958b93

Perhaps it's some bad interaction with rspec-retry or knapsack_pro?

**Comment by sj26** [comment]
Hi Bo! :wave:

Hmm, this seems like a quirk of knapsack pro queue mode.

RSpec formatters operate by dumping information about a suite run — the root xml element corresponds to a suite. It looks like knapsack pro in the configured mode is running multiple suites in the same rspec process. This is not something rspec is really designed to do afaik, they've hacked around it a bit. I think this means it's using the same formatter instance with the same output stream to dump multiple suite summaries, so they're ending up in the same file. The formatter doesn't have control over the output stream, it's just handed one, so I can't make it open different files or anything I'm afraid.

It looks like knapsack pro has a formatter built-in which works around this problem with some very hacky class methods to store results for multiple runs to aggregate them at the end. They also seem to have a hook API — `KnapsackPro::Hooks::Queue.after_queue` looks promising. But this does seem outside the scope of this formatter gem. What do you reckon?

**Comment by bjeanes** [comment]
Maybe there's something that can be interpolated into the file name to
shard better...

That might be a clean solution...

**Comment by sj26** [comment]
That would need to be done above the rspec level inside knapsack pro I think... maybe using those hooks you could find the xml formatter and swap its output?

**Comment by bjeanes** [comment]
Related: https://github.com/KnapsackPro/knapsack_pro-ruby/issues/40

**Comment by bjeanes** [comment]
I'll close this, as clearly the onus is on Knapsack to account for this kind of breakage. Thanks!

**Comment by sj26** [comment]
🙇‍♂️

**Comment by sj26** [comment]
Ah, https://github.com/KnapsackPro/knapsack_pro-ruby/issues/40 seems to be about exactly this issue!

**Comment by ArturT** [comment]
Here is solution how to use junit formatter with knapsack_pro Queue Mode:
https://github.com/KnapsackPro/knapsack_pro-ruby#how-to-use-junit-formatter-with-knapsack_pro-queue-mode

And this is solution for RSpec JSON formatter with knapsack_pro Queue Mode:
https://github.com/KnapsackPro/knapsack_pro-ruby#how-to-use-rspec-json-formatter-with-knapsack_pro-queue-mode

**Comment by bjeanes** [comment]
@ArturT are they newly updated instructions, because I tried those at the time of my last message and did not have success, unfortunately.

**Comment by ArturT** [comment]
@bjeanes I've added only new instructions for JSON formatter.

The [junit formatter instructions](https://github.com/KnapsackPro/knapsack_pro-ruby#how-to-use-junit-formatter-with-knapsack_pro-queue-mode) have been tested and used by multiple users. Maybe you misconfigured something or you have some edge case that no one had yet.

Note it's important to provide `--out` argument to knapsack_pro command:

```
bundle exec rake "knapsack_pro:queue:rspec[--format documentation --format RspecJunitFormatter --out tmp/rspec.xml]"
```

and then set:

```ruby
# spec_helper.rb or rails_helper.rb

# TODO This must be the same path as value for rspec --out argument
# Note the path should not contain sign ~, for instance path ~/project/tmp/rspec.xml may not work. Please use full path instead.
TMP_RSPEC_XML_REPORT = 'tmp/rspec.xml'
# move results to FINAL_RSPEC_XML_REPORT so the results won't accumulate with duplicated xml tags in TMP_RSPEC_XML_REPORT
FINAL_RSPEC_XML_REPORT = 'tmp/rspec_final_results.xml'

KnapsackPro::Hooks::Queue.after_subset_queue do |queue_id, subset_queue_id|
  if File.exist?(TMP_RSPEC_XML_REPORT)
    FileUtils.mv(TMP_RSPEC_XML_REPORT, FINAL_RSPEC_XML_REPORT)
  end
end
```

The only scenario in which knapsack_pro Queue Mode produces broken xml file is when test suite has syntax error but this would happen also without knapsack_pro and RSpec would not start tests at all or produce not completed or invalid xml file.

You can [send me email](https://knapsackpro.com/contact) with your exact configuration file rails_helper.rb and knapsack_pro command you run + xml file you get and I can help debug problem.
