### ISSUE TITLE
frozen-string-literal safe

### ISSUE THREAD

**Issue by tatethurston** [sj26/rspec_junit_formatter#75]
Hi, thanks for this great gem!

Would like to get a discussion going about making this work with RUBYOPT="--enable-frozen-string-literal". 

Here's a good article explaining it: https://freelancing-gods.com/2017/07/27/friendly-frozen-string-literals.html

**Comment by sj26** [comment]
MailCatcher itself is as frozen string literal safe as it can be already. Unfortunately, eventmachine, thin, and several other dependencies are not. :-(

**Comment by sj26** [comment]
I got this totally confused with mailcatcher for a moment, sorry.

https://github.com/sj26/rspec_junit_formatter/commit/1129bf0d5fb4ea292e27210420cf6c315bc9fe63
