### ISSUE TITLE
missing name attribute in testsuite element

### ISSUE THREAD

**Issue by shawnzhu** [sj26/rspec_junit_formatter#9]
I got such error when analyzing the generated rspec.xml report: `Required attribute "name" in element "testsuite" must be set and not be empty.`

Then I found there's no `:name` there in `xml.testsuite` inside j_unit_formatter.rb. It's easy to add the name attribute but I wonder what value it should be especially there're more than one spec.rb file.

**Comment by sj26** [comment]
This was fixed a while ago!

https://github.com/sj26/rspec_junit_formatter/blob/master/lib/rspec_junit_formatter.rb#L20
