### ISSUE TITLE
Full path to failing test

### ISSUE THREAD

**Issue by alienxp03** [sj26/rspec_junit_formatter#99]
I've integrated the gem with my project with a simple line of code, which is great. 

```ruby
## added to rails_helper.b
config.add_formatter(RspecJunitFormatter, 'rspec.xml')
```

This is the output in `rspec.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="rspec" tests="6" skipped="0" failures="1" errors="0" time="0.113422" timestamp="2022-08-19T15:32:22+08:00" hostname="user">
<properties>
<property name="seed" value="41950"/>
</properties>
<testcase classname="spec.models.tag_spec" name="Tag is expected to validate that :tag_type cannot be empty/falsy" file="./spec/models/tag_spec.rb" time="0.008132"></testcase>
<testcase classname="spec.models.tag_spec" name="Tag is expected not to validate that :name cannot be empty/falsy" file="./spec/models/tag_spec.rb" time="0.022748"><failure message="Expected Tag not to validate that :name cannot be empty/falsy, but this
could not be proved.
  After setting :name to ‹nil›, the matcher expected the Tag to be
  valid, but it was invalid instead, producing these validation errors:

  * name: [&quot;can&apos;t be blank&quot;]" type="RSpec::Expectations::ExpectationNotMetError">Failure/Error: it { should_not validate_presence_of(:name) }

  Expected Tag not to validate that :name cannot be empty/falsy, but this
  could not be proved.
    After setting :name to ‹nil›, the matcher expected the Tag to be
    valid, but it was invalid instead, producing these validation errors:

    * name: [&quot;can&apos;t be blank&quot;]
./spec/models/tag_spec.rb:11:in `block (2 levels) in &lt;top (required)&gt;&apos;</failure></testcase>
</testsuite>
```

There are two test cases here. One passed, and one failed. For the failed test, it seems like it doesn't specify which line is failing in the `file` tag. Based on https://github.com/sj26/rspec_junit_formatter/issues/43, it's mentioned that it should. From above example, the line number is only listed on the last line of the error trace. I could parse this to get it, but prefer if there's a nicer & consistent way to get the same result.

Just curious whether this is a bug, or is there a different configuration that I need to do to enable it? On separate note, would be nice to get the line number for all test cases, not just the failing ones.

**Comment by sj26** [comment]
Sorry, the junit specification does not support line numbers in the file path. I hoped it did, but adding line numbers broke some consumers of junit data.

The best place available is within the stack trace.
